[theme]
font = "Nunito:https://fonts.googleapis.com/css2?family=Nunito&display=swap"
font = "sans serif"
backgroundColor = "#e6faf0" 

[theme.sidebar]
font = "Nunito:https://fonts.googleapis.com/css2?family=Nunito&display=swap"
headingFont = "Nunito:https://fonts.googleapis.com/css2?family=Nunito&display=swap"
codeFont = "Nunito:https://fonts.googleapis.com/css2?family=Nunito&display=swap"


